/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/billing/checkout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Checkout */
    post: operations["create_checkout_api_v1_billing_checkout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/billing/checkout/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve Checkout */
    get: operations["retrieve_checkout_api_v1_billing_checkout__session_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/billing/checkout/{session_id}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Complete Mock Checkout */
    post: operations["complete_mock_checkout_api_v1_billing_checkout__session_id__complete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/billing/subscription": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Subscription */
    get: operations["read_subscription_api_v1_billing_subscription_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/billing/webhooks/stripe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Stripe Webhook */
    post: operations["stripe_webhook_api_v1_billing_webhooks_stripe_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/challenges": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Challenges */
    get: operations["list_challenges_api_v1_challenges_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/challenges/{challenge_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Challenge */
    get: operations["get_challenge_api_v1_challenges__challenge_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/challenges/{challenge_id}/run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run Challenge Prompt */
    post: operations["run_challenge_prompt_api_v1_challenges__challenge_id__run_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/community/board": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Board Feed */
    get: operations["read_board_feed_api_v1_community_board_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/community/posts/{post_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Post */
    get: operations["read_post_api_v1_community_posts__post_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/community/shares/{share_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Share */
    get: operations["read_share_api_v1_community_shares__share_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/config/features": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Features */
    get: operations["get_features_api_v1_config_features_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/config/integrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Integration Modes */
    get: operations["get_integration_modes_api_v1_config_integrations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dev/mailbox": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Mailbox */
    get: operations["mailbox_api_v1_dev_mailbox_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dev/mailbox/{message_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Mailbox Message */
    get: operations["mailbox_message_api_v1_dev_mailbox__message_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Live */
    get: operations["live_api_v1_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_api_v1_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/startup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Startup */
    get: operations["startup_api_v1_health_startup_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/integrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Integrations */
    get: operations["integrations_api_v1_integrations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AuthorRead */
    AuthorRead: {
      /** Display Name */
      display_name: string;
      /** Id */
      id: string;
      /** Plan */
      plan: string;
    };
    /** BillingSubscriptionRead */
    BillingSubscriptionRead: {
      /**
       * Customer Email
       * Format: email
       */
      customer_email: string;
      /** Plan */
      plan: string;
      /** Provider */
      provider: string;
      /**
       * Status
       * @enum {string}
       */
      status: "active" | "inactive";
    };
    /** BoardFeedRead */
    BoardFeedRead: {
      date_window?: components["schemas"]["DateWindowRead"] | null;
      /** Posts */
      posts: components["schemas"]["PostRead"][];
      /** Shares */
      shares: components["schemas"]["ShareRead"][];
    };
    /**
     * ChallengeLevel
     * @enum {string}
     */
    ChallengeLevel: "easy" | "medium" | "hard";
    /** ChallengeRead */
    ChallengeRead: {
      /** Challenge Number */
      challenge_number: number;
      /** Content */
      content: string | null;
      /** Id */
      id: string;
      level: components["schemas"]["ChallengeLevel"];
      /** References */
      references: (
        | components["schemas"]["ImgChallengeReferenceRead"]
        | components["schemas"]["VideoChallengeReferenceRead"]
      )[];
      tag: components["schemas"]["ChallengeTag"];
      /** Title */
      title: string;
    };
    /** ChallengeRunRequest */
    ChallengeRunRequest: {
      /** Prompt */
      prompt: string;
      /**
       * Publish To Board
       * @default true
       */
      publish_to_board: boolean;
    };
    /** ChallengeRunResponse */
    ChallengeRunResponse: {
      challenge: components["schemas"]["ChallengeRead"];
      /** Output */
      output: string;
      /** Prompt */
      prompt: string;
      /** Provider */
      provider: string;
      share: components["schemas"]["ChallengeRunShareRead"] | null;
      /** Usage */
      usage: {
        [key: string]: number;
      };
    };
    /** ChallengeRunShareRead */
    ChallengeRunShareRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Id */
      id: string;
      /** Is Public */
      is_public: boolean;
    };
    /** ChallengeSummaryRead */
    ChallengeSummaryRead: {
      /** Challenge Number */
      challenge_number: number;
      /** Id */
      id: string;
      level: components["schemas"]["ChallengeLevel"];
      tag: components["schemas"]["ChallengeTag"];
      /** Title */
      title: string;
    };
    /**
     * ChallengeTag
     * @enum {string}
     */
    ChallengeTag: "ps" | "img" | "video";
    /** CheckoutCreateRequest */
    CheckoutCreateRequest: {
      /**
       * Plan
       * @default pro_monthly
       * @constant
       */
      plan: "pro_monthly";
    };
    /** CheckoutSessionRead */
    CheckoutSessionRead: {
      /** Amount Total */
      amount_total: number | null;
      /** Currency */
      currency: string | null;
      /** Customer Email */
      customer_email: string | null;
      /** Id */
      id: string;
      /** Mode */
      mode: string;
      /** Payment Status */
      payment_status: string;
      /** Provider */
      provider: string;
      /** Status */
      status: string;
      /** Url */
      url: string | null;
    };
    /** DateWindowRead */
    DateWindowRead: {
      /**
       * Date
       * Format: date
       */
      date: string;
      /**
       * End At
       * Format: date-time
       */
      end_at: string;
      /**
       * Start At
       * Format: date-time
       */
      start_at: string;
      /** Timezone */
      timezone: string;
    };
    /** FeatureFlagsRead */
    FeatureFlagsRead: {
      /** Email */
      email: boolean;
      /** Llm */
      llm: boolean;
      /** Payments */
      payments: boolean;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ImgChallengeReferenceRead */
    ImgChallengeReferenceRead: {
      /** File Path */
      file_path: string;
      /** File Type */
      file_type: string;
      /** Id */
      id: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "img";
    };
    /** IntegrationModesRead */
    IntegrationModesRead: {
      /**
       * Email
       * @enum {string}
       */
      email: "mock" | "real";
      /**
       * Google Oauth
       * @enum {string}
       */
      google_oauth: "mock" | "partial" | "real";
      /**
       * Llm
       * @enum {string}
       */
      llm: "mock" | "real";
      /**
       * Payments
       * @enum {string}
       */
      payments: "mock" | "real";
    };
    /** PostRead */
    PostRead: {
      author: components["schemas"]["AuthorRead"];
      challenge: components["schemas"]["ChallengeSummaryRead"] | null;
      /** Content */
      content: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Id */
      id: string;
      tag: components["schemas"]["ChallengeTag"];
      /** Title */
      title: string;
      type: components["schemas"]["PostType"];
    };
    /**
     * PostType
     * @enum {string}
     */
    PostType: "question" | "share";
    /** ShareRead */
    ShareRead: {
      author: components["schemas"]["AuthorRead"];
      challenge: components["schemas"]["ChallengeSummaryRead"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Id */
      id: string;
      /** Is Public */
      is_public: boolean;
      /** Prompt */
      prompt: string | null;
    };
    /** StripeWebhookRead */
    StripeWebhookRead: {
      /** Customer Email */
      customer_email: string | null;
      /** Event Id */
      event_id: string;
      /** Event Type */
      event_type: string;
      /** Processed */
      processed: boolean;
      /** Received */
      received: boolean;
      /** User Id */
      user_id: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VideoChallengeReferenceRead */
    VideoChallengeReferenceRead: {
      /** File Path */
      file_path: string;
      /** File Type */
      file_type: string;
      /** Id */
      id: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "video";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  create_checkout_api_v1_billing_checkout_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckoutCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckoutSessionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  retrieve_checkout_api_v1_billing_checkout__session_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckoutSessionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  complete_mock_checkout_api_v1_billing_checkout__session_id__complete_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckoutSessionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_subscription_api_v1_billing_subscription_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BillingSubscriptionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stripe_webhook_api_v1_billing_webhooks_stripe_post: {
    parameters: {
      query?: never;
      header?: {
        "Stripe-Signature"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StripeWebhookRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_challenges_api_v1_challenges_get: {
    parameters: {
      query?: {
        tag?: components["schemas"]["ChallengeTag"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChallengeRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_challenge_api_v1_challenges__challenge_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        challenge_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChallengeRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  run_challenge_prompt_api_v1_challenges__challenge_id__run_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        challenge_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChallengeRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChallengeRunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_board_feed_api_v1_community_board_get: {
    parameters: {
      query?: {
        limit?: number;
        /** @description Optional user-local board date to filter. */
        date?: string | null;
        /** @description IANA timezone for the date filter. */
        timezone?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BoardFeedRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_post_api_v1_community_posts__post_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        post_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PostRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_share_api_v1_community_shares__share_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        share_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShareRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_features_api_v1_config_features_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeatureFlagsRead"];
        };
      };
    };
  };
  get_integration_modes_api_v1_config_integrations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IntegrationModesRead"];
        };
      };
    };
  };
  mailbox_api_v1_dev_mailbox_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  mailbox_message_api_v1_dev_mailbox__message_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        message_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  live_api_v1_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  ready_api_v1_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  startup_api_v1_health_startup_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  integrations_api_v1_integrations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
