version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      production-dependencies:
        dependency-type: production
        patterns:
          - "*"
      development-dependencies:
        dependency-type: development
        patterns:
          - "*"
  - package-ecosystem: uv
    directory: /apps/api
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"
  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: monthly
    groups:
      pre-commit-hooks:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: monthly
    groups:
      web-base-images:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: monthly
    groups:
      api-base-images:
        patterns:
          - "*"
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: monthly
    groups:
      compose-images:
        patterns:
          - "*"
