// Generated by scripts/generate-web-locales.mjs from src/messages/*.json.
// Do not edit by hand; add or remove locale JSON files instead.
export const locales = ["en"] as const;
export type AppLocale = (typeof locales)[number];
export const defaultLocale: AppLocale = "en";
